### ISSUE TITLE
Decompiler improvements

### ISSUE THREAD

**Issue by plafosse** [Vector35/binaryninja-api#3688]
This is going to be a "living issue" that we'll update as we understand better the particular improvements we're going to focus on:

- [x] Improved address mappings #4191 
- [x] Improved intermediate elimination #4192
- [x] Improved switch processing for sparse cases #4193
- [x] Improved vtable handling #4194

**Comment by ccarpenter04** [comment]
Have you guys decided on a scope of improvements for this milestone yet?
